language: python
sudo: false
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source fluentmetrics -m pytest
  - coverage report -m

after_success:
  - coveralls

