language: python
env:
  global:
  - AWS_DEFAULT_REGION: us-east-1

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis
  - rm -f /etc/boto.cfg

script:
  - tox
  - coverage run --source fluentmetrics -m pytest
  - coverage report -m

after_success:
  - coveralls
